### ISSUE TITLE
COLLECT results aren't stored in slice

### ISSUE THREAD

**Issue by ryanaleksander** [jmcvetta/neoism#100]
Data retrieved from a COLLECT query should be stored in slice in the query result struct. However, when I tried it, it didn't receive any data, the slices remained empty while other properties were filled in just fine

```
type postQueryResult struct {
	Id        string   `json:"post.id"`
	Title     string   `json:"post.title"`
	Detail    string   `json:"post.detail"`
	Type      string   `json:"post.type"`
	Tags      []string `json:"tag.name"`
	CreatedAt string   `json:"rel.at"`
	Upvotes   []string `json:"upvoter.id"`
	Comments  []string `json:"comment.id"`
}

queryResult := []postQueryResult{}

	cq := neoism.CypherQuery{
		Statement: `
			MATCH (:User {id:{id}})-[rel:CREATED]->(post:Post),
		                     (post)-[:TAG]->(tag)
			OPTIONAL MATCH (upvoter:User)-[:UPVOTED]->(post),
			                               (post)-[:HAS_COMMENT]->(comment:Comment)
			RETURN post.id, post.title, post.detail, post.type, rel.at, COLLECT(tag.name), COLLECT(upvoter.id), COLLECT(comment.id)
		`,
		Parameters: neoism.Props{"id": userId},
		Result:     &queryResult,
	}

```

**Comment by mahinko** [comment]
It looks like the column names aren't correct in the result struct. You use the `json:"comment.id"` but you want to collect not the **comment.id** but the **COLLECT(comment.id)**. I would try to name the result in cypher like **COLLECT(comment.id) AS commentIDs** and then use this name in the struct: **`json:"commentIDs"`**

**Comment by ryanaleksander** [comment]
Oh thanks, didn't think of that, it works now.
