### ISSUE TITLE
Does it support Neo4j with self-signed certificates?

### ISSUE THREAD

**Issue by fiatjaf** [jmcvetta/neoism#108]
Apparently it doesn't, as it uses just a normal napping `Session`, and it seems very difficult (impossible?) to pass a custom napping `Session` to the  `Database` object.

Perhaps exporting `connectWithRetry` would make that easier?

**Comment by jmcvetta** [comment]
`Session` is a public member of `Database` object.

**Comment by fiatjaf** [comment]
The problem is that when I create a `Database` object [an HTTP request is made automatically](https://github.com/jmcvetta/neoism/blob/2ffb5c69feb355227c6ee8679768d7289e6d7193/database.go#L45) with the default session object, but it will fail if the certificate is self-signed, right?

Perhaps instead of [creating a `Session` at the time `Database` is being instantiated](https://github.com/jmcvetta/neoism/blob/2ffb5c69feb355227c6ee8679768d7289e6d7193/connect.go#L23-L25) there could be a public variable `neoism.DefaultSession` which we could modify before calling `Connect()`? Something like that would increase flexibility without changing the current API.

**Comment by fiatjaf** [comment]
Solved by calling:

```go
     http.DefaultTransport.(*http.Transport).TLSClientConfig = &tls.Config{
        InsecureSkipVerify: true,
    } 
```

before neoism's `Connect()`.
