### ISSUE TITLE
Credentials in error message (security issue)

### ISSUE THREAD

**Issue by romshark** [jmcvetta/neoism#114]
### Problem
```
if db, err := neoism.Connect(
	options.DatabaseProtocol + "://" +
		creds.Username + ":" + creds.Password + "@" +
		options.DatabaseAddr + "/db/data",
); err != nil {
	return errorLog.Printf(
		"Couldn't establish database connection: %s",
		err,
	)
}
```
The code above produces the following error log entry:
```
Couldn't establish database connection: Get http://neo4j:dev@localhost:7474/db/data/: dial tcp [::1]:32781: connectex: No connection could be made because the target machine actively refused it.
```

Notice that the credentials ("neo4j:dev") are outputted to the error message which is a major security issue that could potentially lead to leaking the credentials into logs.

### Proposed Solution
Check the `uri` via a regexp in `Connect(uri string)` and strip out any credentials if necessary replacing them with a placeholder like `"<credentials>"`

**Comment by jmcvetta** [comment]
Thanks for the bug report!  

Please feel free to implement the recommended fix and submit a PR.
