### ISSUE TITLE
Advanced indexing

### ISSUE THREAD

**Issue by azr** [jmcvetta/neoism#61]
Hello there !

It'd be nice to have an example of how to achieve this with neoism :

http://neo4j.com/docs/stable/indexing-create-advanced.html

Cheers !

**Comment by jmcvetta** [comment]
The REST API [Configurable Legacy Automatic Indexing](http://neo4j.com/docs/stable/rest-api-configurable-auto-indexes.html) docs suggest this feature is unloved and may be removed in the future:

> This technique works, but it is not particularly pleasant. Future versions of Neo4j may remove this loophole in favour of a better structured feature for managing auto-indexing configurations.

Implementing additional Legacy Indexing features is a very low priority for me personally.  But if you would like to submit a PR adding this support, I am am open to including it in Neoism.

**Comment by azr** [comment]
Ah, I didn't see that.
I think just like you : very low priority :)
