### ISSUE TITLE
Support for update statistics?

### ISSUE THREAD

**Issue by jbrukh** [jmcvetta/neoism#68]
Hi there, thank you for this library!

One issue for me is that it is impossible to easily tell if a query resulted in updates in the database (e.g. how many nodes, relationships, labels, properties were added or deleted). Is this supported by the Neo4j REST API?

**Comment by jmcvetta** [comment]
Not sure if this is currently supported.  If it is, a Pull Request implementing it would be happily accepted.  :)

**Comment by MartinGarton** [comment]
I added support for this in https://github.com/jmcvetta/neoism/pull/88 at least for cypher queries.
It's not merged yet, but it would be good if you could try it and let me know of any issues.

**Comment by jmcvetta** [comment]
This functionality is now available in Neoism release v1.3.0.
