### ISSUE TITLE
Neo4j properties can be of many primitive types or an array

### ISSUE THREAD

**Issue by vishalshah-org** [jmcvetta/neoism#70]
the Node.Property() and Relationship.Property() methods are convenient to use for string props but not for non-string props. Have you guys had any discussions on it? Like introducing another method that returns interfaces.. The all props method does however return map[string]interface{}, just thinking if there is a way to make them consistent...

**Comment by vishalshah-org** [comment]
closing at this time as this doesn't appear to be a common issue..

**Comment by jmcvetta** [comment]
If you would love to submit a pull request improving this behavior, I will happily accept it. :-)

**Comment by vishalshah-org** [comment]
will try, adding another set of methods, will leave 2 ways to retrieve props - one that return string (current) and one interfaces.. not sure if thats very intuitive.. i guess.
