### ISSUE TITLE
Neo4j 2.2 connect with username and password

### ISSUE THREAD

**Issue by kostonstyle** [jmcvetta/neoism#75]
Hi
How can I connect the version 2.2 with username and password?

Thanks

**Comment by wwwdata** [comment]
hi, you can specify the username and password in the url like
`http(s)://neo4j:password@server:7474/db/data`

**Comment by jmcvetta** [comment]
@wwwdata thanks for answering!

**Comment by kostonstyle** [comment]
Hi,
how?
