### ISSUE TITLE
Upsert

### ISSUE THREAD

**Issue by gregzuro** [jmcvetta/neoism#78]
Hi,

I am trying to add a Upsert function to this package.  I've copied GetOrCreateNode() as follows:

```
// UpdateOrCreateNode updates a node's properties or creates it if it doesn’t already exist.
func (db *Database) UpdateOrCreateNode(label, key string, p Props) (n *Node, created bool, err error) {

	value, ok := p[key]
	if !ok {
		return nil, false, errors.New("Properties must contain key")
	}
	n = &Node{}
	n.Db = db
	ne := NeoError{}
	uri := join(db.HrefNodeIndex, label) + "?uniqueness=create_or_fail"
	type s struct {
		Key   string      `json:"key"`
		Value interface{} `json:"value"`
		Props Props       `json:"properties"`
	}
	payload := s{
		Key:   key,
		Value: value,
		Props: p,
	}
	fmt.Println(db)
	resp, err := db.Session.Post(uri, &payload, &n, &ne)
	if err != nil {
		return nil, false, err
	}
	switch resp.Status() {
	case 409:

		// update the node since it exists
		existingNode := &Node{}
		resp.Unmarshal(&existingNode)
		existingNode.Db = db
		existingNode.SetProperties(p)
		return existingNode, false, nil // Updated node

	case 201:
		return n, true, nil // Created node
	}
	return nil, false, ne // Error
}
```

Note that with 'create_or_fail' Neo4j returns a 409 (Conflict) but *does* return the node in n.

Napping, however, doesn't unmarshall it:

https://github.com/jmcvetta/napping/blob/master/session.go#L203

Do you have any suggestion re making this less messy in anticipation of pushing it to you?

**Comment by jmcvetta** [comment]
Just looking at the code - I haven't tried this - it looks like Napping will see the 409 response code assume the response payload is an error.  It will therefore try to unmarshall it into the `errMsg` struct rather than `result`.
