### ISSUE TITLE
Error building newest version

### ISSUE THREAD

**Issue by dax0** [jmcvetta/neoism#80]
I'm getting neoism/legacy_index.go:40: not enough arguments in call to resp.EncodingMarshaller.Unmarshal

**Comment by jmcvetta** [comment]
Freaky. More details please.

-- sent from my robot

**Comment by dax0** [comment]
Possible could be because I'm on 1.5beta2

**Comment by jmcvetta** [comment]
Could be. I have only tested the latest code against Neo4j 2.2.4.

Can you tell what has changed? Any way to make it compatible with the older
version without breaking compatibility with current?

-- sent from my robot

**Comment by jmcvetta** [comment]
Or perhaps more likely, you mean the latest Go beta?  Does it work okay for
you with Go 1.4?

-- sent from my robot

**Comment by dax0** [comment]
I'm seeing it on go version go1.4.2 linux/amd64 as well

**Comment by dax0** [comment]
I see an update to Napping that turns Unmarshal to UnmarshalBody is that what the issue is?
