### ISSUE TITLE
Post EOF error

### ISSUE THREAD

**Issue by troq** [jmcvetta/neoism#85]
Neoism sometimes returns the error `Post http://neo4jhost:7474/db/data/cypher: EOF`. It's happened on multiple different queries, so it doesn't seem to be query specific. An example query that failed was 
```
MATCH (d:Dog {name: {name}})
SET d.found = true
```
Rerunning the same query later succeeded. Any ideas as to why this is happening and how I can prevent it?

**Comment by jmcvetta** [comment]
Anything interesting in the Neo4j logs?

Anyone else experiencing this problem?

**Comment by troq** [comment]
For some reason, the most recent logs in console.log and neo4j.0.0.log are only up to August... The neo4j instance is still running fine though. For now I'll fix the logging and keep an eye out for when this bug occurs again.

**Comment by jmcvetta** [comment]
Okay.  Please reopen this bug if you get more info.
