### ISSUE TITLE
replace import "appengine" to "google.golang.org/appengine"

### ISSUE THREAD

**Issue by vishalshah-org** [jmcvetta/neoism#87]
https://github.com/golang/appengine
Those who use godep will encounter this problem especially.
This section has a script to do this as well - https://github.com/golang/appengine#updating-a-go-app-engine-app

Thanks.

PS. https://github.com/golang/oauth2
If you don't want to update your entire app to use the new App Engine packages, you may use both sets of packages in parallel, using only the new packages with the oauth2 package.

**Comment by jmcvetta** [comment]
Thanks.  Please feel free to make this change and submit a Pull Request.
