### ISSUE TITLE
build fails in circleci

### ISSUE THREAD

**Issue by MartinGarton** [jmcvetta/neoism#90]
It seems circleci builds fail, probably due to an upgrade of neo4j to 2.3.1 used during the build.

One of the issues is fixed at https://github.com/jmcvetta/neoism/pull/89

The other is less obvious how to fix. It seems that indexes that are created by the tests do not show up when querying the labels, so they don't get cleaned up by cleanupIndexes().  It's not so obvious how to fix this one.

**Comment by jmcvetta** [comment]
I believe this is fixed now.
