### ISSUE TITLE
neo4j 3.0 bolt protocol support?

### ISSUE THREAD

**Issue by Hokutosei** [jmcvetta/neoism#96]
Greetings,

we're using this driver heavily and the new neo4j 3.0. any updates on how to use the new bolt protocol?

thanks!

**Comment by jmcvetta** [comment]
The new Bolt protocol is not currently supported.  I would be open to adding support, if your company were interested in financially sponsoring the development work.

**Comment by mpmlj** [comment]
@Hokutosei 
I see some guys has already started work on Bolt: https://github.com/johnnadratowski/golang-neo4j-bolt-driver
