### ISSUE TITLE
Multiple relationship is created

### ISSUE THREAD

**Issue by shivendra-it** [jmcvetta/neoism#98]
I am using Relate to connect 2 nodes at run time. If there is any node absent then I have to create it and then Relate. So in this process I am getting multiple edges with same property. Any help??

`func RelateHotelType(typ string,node *neoism.Node){`
  `db, err := neoism.Connect("http://neo4j:12345@localhost:7474")`
  `if err != nil{`
  `  panic(err)`
  `}`
  `var n *neoism.Node`
  `n,check, err1 := db.GetOrCreateNode("HotelType","Type",neoism.Props{"Type": typ})`
`	if err1 != nil {`
`		panic(err1)}`

`if !check {`
`	n.AddLabel("HotelType")`
`}`
`  node.Relate("has_type", n.Id(), neoism.Props{})`
`}`

![a2](https://cloud.githubusercontent.com/assets/8980787/18002535/093ebe82-6ba6-11e6-9434-e0b136f79617.png)

The issue is that if I run it more than once it will duplicate the relationship. Is there a way to create only if the relationship doesn't already exist - something similar to the GetOrCreateNodeFunction.

Or will I have to write some raw cql to check if the relationship already exists before running the statement above?

Thanks in advance

**Comment by jmcvetta** [comment]
The functionality you want doesn't currently exist in Neoism.  It would be pretty cool to have a `GetOrCreateRelationship` function similar to `GetOrCreateNode`.  Please feel free to write that function and submit a PR.  :-)

**Comment by shivendra-it** [comment]
`func GetOrCreateRelationship(from *neoism.Node, to *neoism.Node, relType string, props neoism.Props) (relationship *neoism.Relationship) {
	relationships, err := from.Relationships(relType)

	if err == nil {
		for _, relationship := range relationships {
			endNode, err := relationship.End()

			if err != nil {
				continue
			}

			if endNode.Id() == to.Id() {
				newProps, err := relationship.Properties()

				if err != nil {
					return relationship
				}

				if err := mergo.Merge(&newProps, props); err != nil {
					relationship.SetProperties(newProps)
				}

				return relationship
			}
		}
	}

	relationship, err = from.Relate(relType, to.Id(), props)

	if err != nil {
		log.Printf("Cannot create relationship: %s", err)
	}

	return
}`
